version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    command: uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT}
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:${APP_PORT} | grep -q '404' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo/migrations/0001_init.js:/docker-entrypoint-initdb.d/0001_init.js:ro
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand({ping: 1})' | mongo localhost:${MONGO_PORT}/test --quiet" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo_data:
